services:
  - type: web
    name: ansarhospital
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        value: super-secret-key-here
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_SENDER
        value: ansarhospital@example.com
      - key: EMAIL_SENDER_NAME
        value: Ansar Hospital
      - key: SPREADSHEET_NAME
        value: Database
      - key: GOOGLE_CREDS_JSON
        sync: false
