services:
  - type: web
    name: ansarhospital
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GOOGLE_CREDS_PATH
        value: /etc/secrets/credentials.json
    secretFiles:
      - name: credentials.json
        path: /etc/secrets/credentials.json
