services:
  - type: web
    name: ansar-hospital-app
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials/credentials.json
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_SENDER_NAME
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
    autoDeploy: true
